version: '3.8'

services:
  fashion-assistant:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./checkpoints:/app/checkpoints
      - ./outputs:/app/outputs
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
    command: streamlit run main.py --server.port=8501 --server.address=0.0.0.0

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./checkpoints:/app/checkpoints
    environment:
      - PYTHONPATH=/app
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - redis